sudo: false
language: python
python:
- '3.6'
install:
- python -m pip install setuptools twine
script: true
deploy:
  provider: pypi
  user: borisrozumnuk
  distributions: sdist bdist_wheel
  skip_existing: true
  password:
    secure: orz3996EeBxhdhWmrSJ5U6kje6mi6BGTPjvDvPLQAiIJwcgyuvgO9irTa3DmiXvxHspLwstv4xmYNJTqcGwpOWdHaAHRsGp6m4pJBQM7uTLkBND0wuteIGFe/A4CgTAkHpfIMnI+7WldTvET9FShtD6tQ8Wwnyvvrr14woNWkVh8saGxSkUoY9CK6D8delgLfTEywWBbZJmQMuFnM7aoAULc3uacE/IFnXD7zCaV8t9K52Agl/T6HzPdyoJHTKRFcaFykKENK7yi6dTRRxbBljl/x4Axk2vSPWjYzL2y7GougjgKHFZH7wBIrWhwp37VPc17vklAucmkBmgO/JCsTk282KZoQTudlHnzqcR5quA0LYg3IgkaDLuuv3btUeXdcD2Ht9bDEat8gdVGkgwf6BoaC1XjKj5ldCquXdGEsVjyz/a4RiXsiVmWTGYK93aLa9Rtw2qu0+rS65mQWMaypx1YV8dqd6r8wabmGPH0vUSRn6sj8bh40RAUVdYGl7UtgeqCwOqQzfhI/b8YLsBL3dng+9Ln5+GUhBC8iP01WanzMlYp15JxVr5BnfysEz7RVbrfJEcy+tUmQ+BdThSloPrsoGg2bIv+aF+4TI5H5sHnV+iWlPx2VnmA2tpR2v57fm3VNudGQU/t/fZzCLrnE5s2LU3TCgOoqJw5b8lFkY4=
  only:
  - master
