sudo: false
language: python

python:
  - "3.6"

install:
- python -m pip install setuptools twine
script: true
deploy:
  provider: pypi
  user: borisrozumnuk
  distributions: 'sdist bdist_wheel'
  password:
    secure: H5MoirPg/w8VHt5OkZyVGSlGhrilkCd60n0n4V5tzgz4NTxchWwtJjdKxGp0libI/6J6ec4Klk4QrcXD7nT0KbXajKbFS4kqdRGR91vOAaOfZOstAupM+kmx1hWz93P2e7iDDFgwQPm0jeS0RDu+DUF5c8uAB+bG5CIBuPETeMKiXCccdnJ4jBjG0Q95L8tAELbf5S4i/SnAOwHWBKmsV8WBIM69preciXWeKzcb9FG2UoqzEt7aP6TD9/UxoIvPm8JVlA2YCGsIcwTF/SiqXP4LhiEIDAE8hjK3PsM/KzLH2HntLX9lrekou2MpaiqUaVu21g1X0+/d2l/MthJjEmezOFohDuHLNHqHkVxN3iOq6ZfEhqouYEwAHFF6dIXdUXHSnbElH7KUX1X5ch0MyUqhBKEoVjA8567ACq7c9VqkV4+wxkGb9EvyYO8MUC0eniy20pB4oMxdDMHPqocLAteSKN6Y0YlmfrKbRknZfYZSP994LAT6EtykXti8H3hivsPO9WN4XRwJzUx2JarGuGmbk8+d0SmrrrLSEQ5yKF0piy07WB//9aMF35/J3iidSr3EL44SjJLGCW3NGXKwbW4jXBZO79wsadSib0IDjGGiXGtfYFO7Aobi4b9VF13Hc4A5Iu2gUboNBZXMEQReE3ivazvmG2mhvOBYd9rSc04=
